def traducir(palabra):

    p = palabra.lower().strip()

    dic = {
        # Personas y cuerpo
        "person": "persona",
        "man": "hombre",
        "woman": "mujer",
        "girl": "niña",
        "boy": "niño",
        "child": "niño",
        "baby": "bebé",
        "face": "rostro",
        "forehead": "frente",
        "head": "cabeza",
        "hair": "cabello",
        "ear": "oreja",
        "eye": "ojo",
        "nose": "nariz",
        "mouth": "boca",
        "hand": "mano",
        "arm": "brazo",
        "finger": "dedo",
        "leg": "pierna",
        "foot": "pie",
        "shoe": "zapato",
        "shirt": "camiseta",
        "tshirt": "camiseta",
        "jeans": "jeans",
        "trousers": "pantalón",
        "dress": "vestido",
        "skirt": "falda",
        "coat": "abrigo",
        "jacket": "chaqueta",
        "hat": "sombrero",
        "glasses": "gafas",
        "sunglasses": "gafas de sol",
        "backpack": "mochila",
        "bag": "bolso",
        "handbag": "cartera",
        "watch": "reloj",
        "bracelet": "pulsera",

        # Objetos comunes
        "book": "libro",
        "magazine": "revista",
        "poster": "poster",
        "paper": "papel",
        "paper product": "producto de papel",
        "document": "documento",
        "handwriting": "escritura a mano",
        "label": "etiqueta",
        "package": "paquete",
        "box": "caja",
        "bottle": "botella",
        "cup": "taza",
        "mug": "taza",
        "glass": "vaso",
        "plate": "plato",
        "bowl": "bandeja",
        "spoon": "cuchara",
        "fork": "tenedor",
        "knife": "cuchillo",
        "bottled and jarred packaged goods": "productos embotellados y envasados",


        # Comida
        "food": "comida",
        "fruit": "fruta",
        "banana": "banana",
        "apple": "manzana",
        "orange": "naranja",
        "lemon": "limón",
        "grape": "uva",
        "watermelon": "sandía",
        "strawberry": "fresa",
        "pineapple": "pina",
        "bread": "pan",
        "sandwich": "sanduche",
        "pizza": "pizza",
        "hamburger": "hamburguesa",
        "meat": "carne",
        "fish": "pescado",

        # Hogar
        "chair": "silla",
        "table": "mesa",
        "desk": "escritorio",
        "bed": "cama",
        "pillow": "almohada",
        "sofa": "sof+a",
        "couch": "sofá",
        "lamp": "lampara",
        "window": "ventana",
        "door": "puerta",
        "wall": "pared",
        "ceiling": "techo",
        "floor": "piso",
        "carpet": "alfombra",
        "mirror": "espejo",
        "tv": "televisor",
        "monitor": "monitor",
        "computer": "computadora",
        "keyboard": "teclado",
        "mouse": "ratón",
        "phone": "teléfono",
        "smartphone": "teléfono",
        "remote": "control remoto",
        "camera": "cámara",

        # Cocina
        "stove": "cocina",
        "oven": "horno",
        "microwave": "microondas",
        "refrigerator": "refrigerador",
        "fridge": "refrigerador",
        "sink": "lavaplatos",
        "faucet": "grifo",

        # Baño
        "toilet": "inodoro",
        "shower": "ducha",
        "towel": "toalla",

        # Transporte
        "car": "carro",
        "truck": "camión",
        "bus": "bus",
        "motorcycle": "motocicleta",
        "bike": "bicicleta",
        "bicycle": "bicicleta",
        "train": "tren",
        "airplane": "avión",
        "boat": "barco",

        # Escenas y lugares
        "street": "calle",
        "road": "carretera",
        "traffic sign": "señal de tráfico",
        "stop sign": "señal de alto",
        "building": "edificio",
        "house": "casa",
        "store": "tienda",
        "shop": "tienda",
        "supermarket": "supermercado",
        "parking lot": "estacionamiento",

        # Naturaleza
        "tree": "árbol",
        "plant": "planta",
        "flower": "flor",
        "grass": "cesped",
        "sky": "cielo",
        "cloud": "nube",
        "sun": "sol",
        "moon": "luna",
        "mountain": "montana",
        "water": "agua",
        "river": "río",
        "beach": "playa",

        # Animales
        "dog": "perro",
        "cat": "gato",
        "bird": "ave",
        "fish animal": "pez",
        "horse": "caballo",
        "cow": "vaca",
        "sheep": "oveja",
        "goat": "cabra",
        "chicken": "gallina",
        "duck": "pato",

        # Conceptos comunes
        "self help": "autoayuda",
        "fiction": "ficci+on",
        "nonfiction": "no ficción",
        "packaged goods": "productos empaquetados",
        "clothing": "ropa",
        "furniture": "muebles",
        "electronics": "electrónicos",
        "technology": "tecnología",
        "indoor": "interior",
        "outdoor": "exterior",
        "toy": "juguete",
        "tool": "herramienta",
        "machine": "máquina",

        # Colores
        "color": "color",
        "black": "negro",
        "white": "blanco",
        "gray": "gris",
        "grey": "gris",
        "red": "rojo",
        "blue": "azul",
        "green": "verde",
        "yellow": "amarillo",
        "orange": "naranja",
        "pink": "rosado",
        "purple": "morado",
        "violet": "violeta",
        "brown": "cafe",
        "beige": "beige",
        "cream": "crema",
        "gold": "dorado",
        "silver": "plateado",

        # Tonos y variaciones
        "light": "claro",
        "dark": "oscuro",
        "bright": "brillante",
        "pale": "palido",
        "deep": "intenso",
        "soft": "suave",

        # Combinaciones comunes
        "light blue": "azul claro",
        "dark blue": "azul oscuro",
        "light green": "verde claro",
        "dark green": "verde oscuro",
        "light gray": "gris claro",
        "dark gray": "gris oscuro",
        "light brown": "caf+e claro",
        "dark brown": "café oscuro",

        # Mano y gestos
        "nail": "uña",
        "gesture": "gesto",
        "wrist": "muñeca",
        "thumb": "pulgar",
        "sign language": "lenguaje de señas",
        "symbol": "símbolo",
        "v sign": "señal de v",
        "peace": "paz",
        "thumb signal": "dedo pulgar arriba",

        # Tecnología y dispositivos
        "gadget": "dispositivo",
        "electronic device": "dispositivo electrónico",
        "mobile phone": "teléfono móvil",
        "telephony": "telefonía",
        "communication device": "dispositivo de comunicación",
        "portable communications device": "dispositivo portátil de comunicación",
        "mobile device": "dispositivo móvil",
        "display device": "dispositivo de pantalla",
        "screen": "pantalla",
        "touchscreen": "pantalla táctil",

        # Códigos y etiquetas
        "1d barcode": "código de barras unidimensional",


    }

    return dic.get(p, p)
